const dados = [
 {
  "COD PRODUTO": 279,
  "NOME": "BRAHMA CHOPP LONG NECK 355ML SIX-PACK CAIXA C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 371,
  "NOME": "MALZBIER BRAHMA LONG NECK 355ML SIX-PACK BANDEJA C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 392,
  "NOME": "SKOL LONG NECK 355ML SIX-PACK CAIXA C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 620,
  "NOME": "CARACU LONG NECK 355ML SIX-PACK BANDEJA C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 982,
  "NOME": "SKOL 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 987,
  "NOME": "MALZBIER BRAHMA 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 988,
  "NOME": "BRAHMA CHOPP 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 1388,
  "NOME": "SKOL GFA VD 1L 2,99",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 1695,
  "NOME": "BRAHMA CHOPP GFA VD 1L COM TTC",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 1743,
  "NOME": "ANTARCTICA PILSEN GFA VD 1L COM TTC",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 1744,
  "NOME": "POLAR EXPORT GFA VD 1L COM TTC",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 2538,
  "NOME": "ANTARCTICA PILSEN 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 2006,
  "NOME": "ANTARCTICA SUBZERO 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 2544,
  "NOME": "EXTRA SERRAMALTE 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 2545,
  "NOME": "POLAR EXPORT 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 2546,
  "NOME": "ORIGINAL 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 2548,
  "NOME": "BUDWEISER 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 2868,
  "NOME": "POLAR EXPORT LONG NECK 355ML SIX-PACK BANDEJA C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 3733,
  "NOME": "BOHEMIA NOVA EMBALAGEM 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 3735,
  "NOME": "BOHEMIA NOVA EMBALAGEM LONG NECK 355ML SIX-PACK SHRINK C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 8153,
  "NOME": "STELLA ARTOIS LONG NECK 275ML SIX PACK CX04",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 91,
  "LASTRO": 13
 },
 {
  "COD PRODUTO": 8336,
  "NOME": "ORIGINAL ONE WAY 600ML CX 12",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 75,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 8919,
  "NOME": "GUARANA CHP ANTARCTICA PET 600ML CX12 NPAL",
  "EMBALAGEM": "600ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 144,
  "LASTRO": 18
 },
 {
  "COD PRODUTO": 8921,
  "NOME": "GUARANA CHP ANTARCTICA DIET PET 600ML CX12 NPAL",
  "EMBALAGEM": "600ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 144,
  "LASTRO": 18
 },
 {
  "COD PRODUTO": 8923,
  "NOME": "PEPSI COLA PET 600ML CX12 NPAL",
  "EMBALAGEM": "600ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 144,
  "LASTRO": 18
 },
 {
  "COD PRODUTO": 8926,
  "NOME": "PEPSI TWIST PET 600ML CX12 NPAL",
  "EMBALAGEM": "600ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 144,
  "LASTRO": 18
 },
 {
  "COD PRODUTO": 8931,
  "NOME": "SUKITA PET 600ML CX12 NPAL",
  "EMBALAGEM": "600ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 144,
  "LASTRO": 18
 },
 {
  "COD PRODUTO": 8933,
  "NOME": "SODA LIMONADA ANTARCTICA PET 600ML CX12 NPAL",
  "EMBALAGEM": "600ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 144,
  "LASTRO": 18
 },
 {
  "COD PRODUTO": 9068,
  "NOME": "SKOL LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9069,
  "NOME": "BRAHMA CHOPP LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9071,
  "NOME": "CARACU LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9072,
  "NOME": "BOHEMIA NOVA EMBALAGEM LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9079,
  "NOME": "POLAR EXPORT LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9081,
  "NOME": "MALZBIER BRAHMA LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9083,
  "NOME": "SKOL LT 473ML SH C\/12 NPAL",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9259,
  "NOME": "SKOL LATA 350ML SH C\/18 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 195,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 9320,
  "NOME": "BRAHMA CHOPP LT 473ML SH C\/12 NPAL",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9427,
  "NOME": "ANTARCTICA PILSEN LT 473ML SH C\/12 NPAL",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9431,
  "NOME": "POLAR EXPORT LT 473ML SH C\/12 NPAL",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9886,
  "NOME": "BRAHMA CHOPP LATA 350ML SH C\/18 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 195,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 10175,
  "NOME": "ANTARCTICA SUBZERO LT 473ML SH C\/12 NPAL",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 10537,
  "NOME": "BOHEMIA GFA VD 990ML",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 10539,
  "NOME": "BUDWEISER LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 11371,
  "NOME": "BUDWEISER LN 343ML SIXPACK CARTAO SH C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 12948,
  "NOME": "BRAHMA CHOPP ZERO LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 12951,
  "NOME": "BRAHMA CHOPP ZERO LN 355ML SIXPACK CX CART C\/04",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 13201,
  "NOME": "BRAHMA CHOPP GFA VD 300ML CX C\/23",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 90,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 13205,
  "NOME": "SKOL GFA VD 300ML CX C\/23",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 90,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 13307,
  "NOME": "BUDWEISER GFA VD 990ML CX C\/12",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 13572,
  "NOME": "SKOL BEATS SENSES LONG NECK 313ML SIX-PACK SH C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 13578,
  "NOME": "BRAHMA CHOPP ZERO GFA VD 300ML CX C\/23",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 90,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 13827,
  "NOME": "CORONA EXTRA LONG NECK 355ML SIX-PACK C\/4 - CX70 AUSTRALIA",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 70,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 14074,
  "NOME": "BRAHMA EXTRA LAGER 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 14099,
  "NOME": "BUDWEISER ONE WAY 600ML CX C\/12 NPAL",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 80,
  "LASTRO": 16
 },
 {
  "COD PRODUTO": 14117,
  "NOME": "BRAHMA EXTRA LAGER LONG NECK 355ML SIX-PACK SHRINK C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 14120,
  "NOME": "BRAHMA EXTRA WEISS LONG NECK 355ML SIX-PACK SHRINK C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 14123,
  "NOME": "BRAHMA EXTRA RED LAGER LONG NECK 355ML SIX-PACK SHRINK C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 14340,
  "NOME": "ORIGINAL ONE WAY 300ML CXPAP12",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 176,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 15054,
  "NOME": "EXTRA SERRAMALTE ONE WAY 600ML CX 12",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 75,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 15778,
  "NOME": "BRAHMA EXTRA LAGER LATA 350ML CX CARTAO C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 17264,
  "NOME": "BRAHMA EXTRA LAGER LT 473ML CX CARTAO C\/12",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 17266,
  "NOME": "BOHEMIA LT 473ML CX CARTAO C\/12",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 18062,
  "NOME": "POLAR EXPORT GFA VD 300ML CX C\/23",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 90,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 1684,
  "NOME": "SKOL ONE WAY 1L CXPAPC\/12",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 10530,
  "NOME": "ANTARCTICA SUBZERO GFA VD 1L",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 11518,
  "NOME": "SKOL ONE WAY 300ML CXPAP12",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 176,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 14548,
  "NOME": "COLORADO CAUIM ONE WAY 600ML CX C-12 ARTE",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 14550,
  "NOME": "COLORADO APPIA ONE WAY 600ML CX C-12 ARTE",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 14552,
  "NOME": "COLORADO INDICA ONE WAY 600ML CX C-12 ARTE",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 19166,
  "NOME": "COLORADO LAGER ONE WAY 600ML CX C-12 ARTE",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 12604,
  "NOME": "PATAGONIA BOHEIMIAN PILSENER ONE WAY 740ML CX6",
  "EMBALAGEM": 740,
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 140,
  "LASTRO": 28
 },
 {
  "COD PRODUTO": 12602,
  "NOME": "PATAGONIA AMBER LAGER ONE WAY 740ML CX6",
  "EMBALAGEM": 740,
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 140,
  "LASTRO": 28
 },
 {
  "COD PRODUTO": 12882,
  "NOME": "PATAGONIA WEISSE ONE WAY 740ML CX6",
  "EMBALAGEM": 740,
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 140,
  "LASTRO": 28
 },
 {
  "COD PRODUTO": 14109,
  "NOME": "WALS WITTE ONE WAY 600ML CX C\/12 ARTE",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 14111,
  "NOME": "WALS BOHEMIA PILSEN ONE WAY 600ML CX C\/12 ARTE",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 13843,
  "NOME": "EXTRA SERRAMALTE ONE WAY 300ML CXPAP12",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 176,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 14135,
  "NOME": "BUDWEISER LATA 473ML SIX-PACK SH C\/2 NPAL",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9067,
  "NOME": "ANTARCTICA PILSEN LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9448,
  "NOME": "BOHEMIA ESCURA LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9084,
  "NOME": "GUARANA CHP ANTARCTICA LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "REFRI LATA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9085,
  "NOME": "GUARANA CHP ANTARCTICA DIET LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "REFRI LATA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9087,
  "NOME": "SODA LIMONADA ANTARCTICA LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "REFRI LATA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9089,
  "NOME": "SUKITA LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "REFRI LATA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9096,
  "NOME": "PEPSI COLA LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "REFRI LATA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9274,
  "NOME": "PEPSI ZERO LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "REFRI LATA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9093,
  "NOME": "PEPSI TWIST LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "REFRI LATA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9090,
  "NOME": "TEEM LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "350ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9091,
  "NOME": "TONICA ANTARCTICA LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "REFRI LATA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 9092,
  "NOME": "TONICA ANTARCTICA DIET LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "REFRI LATA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 8791,
  "NOME": "H2OH LIMAO C\/GAS PET 500ML CAIXA C\/12",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 168,
  "LASTRO": 24
 },
 {
  "COD PRODUTO": 13061,
  "NOME": "H2OH LIMONETO PET 500ML SHRINK C\/12 NPAL",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 168,
  "LASTRO": 24
 },
 {
  "COD PRODUTO": 7980,
  "NOME": "GATORADE TANGERINA PET 500ML SIXPACK",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 42
 },
 {
  "COD PRODUTO": 7981,
  "NOME": "GATORADE LARANJA PET 500ML SIXPACK",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 42
 },
 {
  "COD PRODUTO": 7981,
  "NOME": "GATORADE LARANJA PET 500ML SIXPACK",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 42
 },
 {
  "COD PRODUTO": 7982,
  "NOME": "GATORADE LIMAO PET 500ML SIXPACK",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 42
 },
 {
  "COD PRODUTO": 7983,
  "NOME": "GATORADE MORANGO-MARACUJA PET 500ML SIXPACK",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 42
 },
 {
  "COD PRODUTO": 7977,
  "NOME": "GATORADE UVA PET 500ML SIXPACK",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 42
 },
 {
  "COD PRODUTO": 2585,
  "NOME": "GUARANA CHP ANTARCTICA GFA VD 1L",
  "EMBALAGEM": "1L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 11593,
  "NOME": "PEPSI COLA GFA VD 1L",
  "EMBALAGEM": "1L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 10746,
  "NOME": "GUARANA CHP ANTARCTICA ONE WAY 1L GRFE CX C\/12",
  "EMBALAGEM": "1L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 13213,
  "NOME": "PEPSI COLA ONE WAY 1L GRFE CX C\/12",
  "EMBALAGEM": "1L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 2132,
  "NOME": "GUARANA CHP ANTARCTICA PET 1L CAIXA C\/6 NOVA RIO",
  "EMBALAGEM": "1L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 175,
  "LASTRO": 25
 },
 {
  "COD PRODUTO": 7703,
  "NOME": "PEPSI COLA PET 1L CAIXA C\/6",
  "EMBALAGEM": "1L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 175,
  "LASTRO": 25
 },
 {
  "COD PRODUTO": 253,
  "NOME": "SUKITA PET 1L CAIXA C\/6",
  "EMBALAGEM": "1L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 175,
  "LASTRO": 25
 },
 {
  "COD PRODUTO": 8411,
  "NOME": "GUARANA CHP ANTARCTICA PET 1,5 SHRINK C\/6",
  "EMBALAGEM": "1,5L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 115,
  "LASTRO": 23
 },
 {
  "COD PRODUTO": 8418,
  "NOME": "PEPSI COLA PET 1500 CX06",
  "EMBALAGEM": "1,5L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 115,
  "LASTRO": 23
 },
 {
  "COD PRODUTO": 8793,
  "NOME": "H2OH LIMAO C\/GAS PET 1,5L CAIXA C\/6",
  "EMBALAGEM": "1,5L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 115,
  "LASTRO": 23
 },
 {
  "COD PRODUTO": 13065,
  "NOME": "H2OH LIMONETO PET 1,5 SHRINK C\/06 NPAL",
  "EMBALAGEM": "1,5L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 115,
  "LASTRO": 23
 },
 {
  "COD PRODUTO": 930,
  "NOME": "PEPSI COLA PET 2L CAIXA C\/8",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 75,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 9277,
  "NOME": "PEPSI ZERO PET 2L SHRINK C\/8",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 75,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 5029,
  "NOME": "PEPSI TWIST PET 2L SHRINK C\/8",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 75,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 2937,
  "NOME": "GUARANA CHP ANTARCTICA PET 2L SHRINK C\/8",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 75,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 2938,
  "NOME": "GUARANA CHP ANTARCTICA DIET PET 2L SHRINK C\/8",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 75,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 232,
  "NOME": "TEEM PET 2L CAIXA C\/8",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 75,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 2940,
  "NOME": "SODA LIMONADA ANTARCTICA PET 2L SHRINK C\/8",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 75,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 1232,
  "NOME": "SUKITA UVA PET 2L CAIXA C\/8",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 75,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 856,
  "NOME": "SUKITA PET 2L CAIXA C\/8",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 75,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 7945,
  "NOME": "PEPSI COLA PET 2,5L CAIXA C\/6",
  "EMBALAGEM": "2,5L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 64,
  "LASTRO": 16
 },
 {
  "COD PRODUTO": 7947,
  "NOME": "GUARANA CHP ANTARCTICA PET 2,5L CAIXA C\/6",
  "EMBALAGEM": "2,5L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 64,
  "LASTRO": 16
 },
 {
  "COD PRODUTO": 6903,
  "NOME": "FONTE DA ILHA AGUA M SG PVC 500ML CAIXA C\/12.",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 175,
  "LASTRO": 25
 },
 {
  "COD PRODUTO": 6905,
  "NOME": "FONTE  DA ILHA AGUA M CG PVC 500ML CAIXA C\/12.",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 175,
  "LASTRO": 25
 },
 {
  "COD PRODUTO": 15414,
  "NOME": "FONTE DA ILHA AGUA M SG PET 500ML CX C-12 PREMIUM",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 140,
  "LASTRO": 20
 },
 {
  "COD PRODUTO": 15416,
  "NOME": "FONTE  DA ILHA AGUA M CG PET 500ML CX C-12 PREMIUM",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 140,
  "LASTRO": 20
 },
 {
  "COD PRODUTO": 6907,
  "NOME": "FONTE DA ILHA AGUA M SG PVC 1,5L CAIXA C\/06",
  "EMBALAGEM": "1,5L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 125,
  "LASTRO": 25
 },
 {
  "COD PRODUTO": 6909,
  "NOME": "FONTE  DA ILHA AGUA M CG PVC 2L CAIXA C\/06",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 100,
  "LASTRO": 20
 },
 {
  "COD PRODUTO": 18278,
  "NOME": "SKOL HOPS LATA 350ML CX CARTAO C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 18388,
  "NOME": "SKOL HOPS LT 473ML SH C\/12 NPAL",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 17808,
  "NOME": "BUDWEISER OW 330ML CX C\/24",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 18114,
  "NOME": "SKOL HOPS 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 18135,
  "NOME": "SERRAMALTE LATA 350ML SIX-PACK SH C\/2 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 17268,
  "NOME": "PATAGONIA BOH PILS NACIONAL LN 355ML CX C\/12",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 132,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 17278,
  "NOME": "PATAGONIA WEISSE NACIONAL LN 355ML CX C\/12",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 132,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 17276,
  "NOME": "PATAGONIA AMB LAG NACIONAL LN 355ML CX C\/12",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 132,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 17608,
  "NOME": "SKOL LONG NECK 275ML SIX PACK CX04",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 91,
  "LASTRO": 13
 },
 {
  "COD PRODUTO": 18152,
  "NOME": "GUARANA CHP ANTARCTICA PET 200ML SH C\/12",
  "EMBALAGEM": "CAÇULINHA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 400,
  "LASTRO": 40
 },
 {
  "COD PRODUTO": 18266,
  "NOME": "PEPSI COLA PET 200ML SH C\/12",
  "EMBALAGEM": "CAÇULINHA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 400,
  "LASTRO": 40
 },
 {
  "COD PRODUTO": 18267,
  "NOME": "SODA LIMONADA ANTARCTICA PET 200ML SH C\/12",
  "EMBALAGEM": "CAÇULINHA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 400,
  "LASTRO": 40
 },
 {
  "COD PRODUTO": 18268,
  "NOME": "SUKITA PET 200ML SH C\/12",
  "EMBALAGEM": "CAÇULINHA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 400,
  "LASTRO": 40
 },
 {
  "COD PRODUTO": 18490,
  "NOME": "PATAGONIA AMB LAG NACIONAL LATA 473ML 6PACK CARTAO",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 420,
  "LASTRO": 42
 },
 {
  "COD PRODUTO": 18676,
  "NOME": "SKOL PURO MALTE LT 473ML SH C\/12 NPAL",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 18680,
  "NOME": "SKOL PURO MALTE LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 18677,
  "NOME": "SKOL PURO MALTE 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 18678,
  "NOME": "SKOL PURO MALTE GFA VD 1L",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 18673,
  "NOME": "SKOL PURO MALTE GFA VD 300ML CX C\/23",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 90,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 19310,
  "NOME": "ORIGINAL LATA 350ML CX CARTAO C\/12 NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 286,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 18833,
  "NOME": "SKOL PURO MALTE LONG NECK 275ML SIX PACK CX04 PULL OFF",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 91,
  "LASTRO": 13
 },
 {
  "COD PRODUTO": 18750,
  "NOME": "PATAGONIA BOH PILS NACIONAL ONE WAY 740ML CX6",
  "EMBALAGEM": 740,
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 140,
  "LASTRO": 28
 },
 {
  "COD PRODUTO": 18752,
  "NOME": "PATAGONIA WEISSE NACIONAL ONE WAY 740ML CX6",
  "EMBALAGEM": 740,
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 140,
  "LASTRO": 28
 },
 {
  "COD PRODUTO": 18772,
  "NOME": "PATAGONIA AMB LAG NACIONAL ONE WAY 740ML CX6",
  "EMBALAGEM": 740,
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 140,
  "LASTRO": 28
 },
 {
  "COD PRODUTO": 17757,
  "NOME": "BECKS N LONG NECK 330ML SIX-PACK SHRINK C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 14724,
  "NOME": "BECKS LONG NECK 275ML SIX PACK CX04 TRAY INT",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 91,
  "LASTRO": 13
 },
 {
  "COD PRODUTO": 18836,
  "NOME": "CORONA EXTRA N LONG NECK 330ML CX C\/24 NPAL",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 19227,
  "NOME": "RED BULL BR LATA 355ML FOUR PACK .",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 624,
  "LASTRO": 78
 },
 {
  "COD PRODUTO": 19228,
  "NOME": "RED BULL BR LATA 250ML FOUR PACK NPAL .",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 864,
  "LASTRO": 96
 },
 {
  "COD PRODUTO": 19229,
  "NOME": "RED BULL BR LATA 250ML SIX PACK NPAL .",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 576,
  "LASTRO": 64
 },
 {
  "COD PRODUTO": 19225,
  "NOME": "RED BULL BR LATA 250ML CX C 24 NPAL .",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 144,
  "LASTRO": 16
 },
 {
  "COD PRODUTO": 19231,
  "NOME": "RED BULL SUGAR FREE BR LATA 250ML FOUR PACK NPAL .",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 864,
  "LASTRO": 96
 },
 {
  "COD PRODUTO": 19164,
  "NOME": "GUARANA CHP ANTARCTICA PET 1L PACK C\/2 MULTPACK",
  "EMBALAGEM": "1L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 525,
  "LASTRO": 75
 },
 {
  "COD PRODUTO": 19312,
  "NOME": "PEPSI COLA PET 1L PACK C\/2 MULTPACK",
  "EMBALAGEM": "1L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 525,
  "LASTRO": 75
 },
 {
  "COD PRODUTO": 16503,
  "NOME": "BOHEMIA GFA VD 300ML CX C\/23",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 90,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 20498,
  "NOME": "BRAHMA DUPLO MALTE LT SLEEK 350ML SH C 12",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 280,
  "LASTRO": 28
 },
 {
  "COD PRODUTO": 20072,
  "NOME": "BECKS N LT SLEEK 350ML C 8 CX CARTAO",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 400,
  "LASTRO": 40
 },
 {
  "COD PRODUTO": 20329,
  "NOME": "BRAHMA DUPLO MALTE 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 21275,
  "NOME": "BRAHMA DUPLO MALTE ONE WAY 600ML CX 12",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 75,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 21116,
  "NOME": "SKOL BEATS GT LONG NECK 313ML SIX-PACK SH C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 18765,
  "NOME": "PATAGONIA WEISSE NACIONAL LATA 473ML 6PACK CARTAO",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 420,
  "LASTRO": 42
 },
 {
  "COD PRODUTO": 18341,
  "NOME": "PEPSI COLA PET 3000 ML C\/04 SHRINK LISO .",
  "EMBALAGEM": "3L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 80,
  "LASTRO": 20
 },
 {
  "COD PRODUTO": 18137,
  "NOME": "GUARANA CHP ANTARCTICA PET 3L C\/04 SHRINK LISO",
  "EMBALAGEM": "3L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 80,
  "LASTRO": 20
 },
 {
  "COD PRODUTO": 21666,
  "NOME": "RED BULL TROPICAL BR LATA 250ML FOUR PACK NPAL .",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 864,
  "LASTRO": 96
 },
 {
  "COD PRODUTO": 18764,
  "NOME": "PATAGONIA BOH PILS NACIONAL LATA 473ML 6PACK CARTAO",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 420,
  "LASTRO": 42
 },
 {
  "COD PRODUTO": 18144,
  "NOME": "SERRANA LT 473ML SH C\/12 NPAL",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 20544,
  "NOME": "BRAHMA DUPLO MALTE LONG NECK 330ML SIX-PACK SHRINK C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 21119,
  "NOME": "SKOL BEATS GT LT 269ML CX CARTAO C\/8 NPAL",
  "EMBALAGEM": "LATA 269",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 520,
  "LASTRO": 40
 },
 {
  "COD PRODUTO": 11721,
  "NOME": "GUARANA CHP ANTARCTICA PET 500ML SHRINK C\/12 NPAL",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 168,
  "LASTRO": 24
 },
 {
  "COD PRODUTO": 18807,
  "NOME": "STELLA ARTOIS LONG NECK 330ML SIX-PACK SHRINK C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 19849,
  "NOME": "BOHEMIA_ LT SLEEK 350ML SH C 12",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 280,
  "LASTRO": 28
 },
 {
  "COD PRODUTO": 20853,
  "NOME": "COLORADO LAGER LT SLEEK 350ML C 8 CX CARTAO",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 400,
  "LASTRO": 40
 },
 {
  "COD PRODUTO": 21501,
  "NOME": "COLORADO LAGER LN 355ML CX C\/12",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 132,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 22641,
  "NOME": "PRESIDENTE CONHAQ GARRAFA VIDRO 900ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 720,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 21789,
  "NOME": "ORLOFF GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 576,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 22545,
  "NOME": "COROTE COQUETEL LIMAO GARRAFA PET 500 ML CX C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 168,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 22549,
  "NOME": "COROTE COQUETEL MORANGO GARRAFA PET 500 ML CX C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 168,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 22550,
  "NOME": "COROTE COQUETEL BLUEBERRY GARRAFA PET 500 ML CX C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 168,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 22551,
  "NOME": "COROTE COQUETEL TUTTI FRUTTI GARRAFA PET 500 ML CX C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 168,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 22835,
  "NOME": "COROTE CACHACA GARRAFA PET 500 ML CX C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 168,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 22382,
  "NOME": "PASSPORT SELECTION GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 576,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 21529,
  "NOME": "ABSOLUT ORIGINAL GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 480,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 21776,
  "NOME": "SELETA PRATA GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 900,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 21956,
  "NOME": "BALLANTINES 12 YEARS GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 480,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 21887,
  "NOME": "ORLOFF DRY GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 576,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 21886,
  "NOME": "BEEFEATER LONDON DRY GARRAFA VIDRO 750ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 816,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 13566,
  "NOME": "SKOL BEATS SENSES LT 269ML CX C\/8 FRIDGE PACK",
  "EMBALAGEM": "LATA 269",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 520,
  "LASTRO": 40
 },
 {
  "COD PRODUTO": 20248,
  "NOME": "MIKES HARD LEMONADE N LONG NECK 275ML CX C\/6",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 300,
  "LASTRO": 51
 },
 {
  "COD PRODUTO": 21113,
  "NOME": "STELLA ARTOIS SEM GLUTEN LONG NECK 330ML SIX-PACK SHRINK C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 84,
  "LASTRO": 12
 },
 {
  "COD PRODUTO": 19644,
  "NOME": "SKOL PURO MALTE LT SLEEK 350ML SH C 12",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 280,
  "LASTRO": 28
 },
 {
  "COD PRODUTO": 21788,
  "NOME": "BALLANTINES FINEST GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 480,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 21955,
  "NOME": "CHIVAS REGAL 12 ANOS GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 384,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 23233,
  "NOME": "NATU NOBILIS APERITIVO GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 540,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 23256,
  "NOME": "PIRACANJUBA CREME DE LEITE TETRAPAK 200G CX C\/27",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 180,
  "LASTRO": 576
 },
 {
  "COD PRODUTO": 23246,
  "NOME": "PIRACANJUBA LEITE CONDENSADO TETRAPAK 395G CX C\/27",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 105,
  "LASTRO": 576
 },
 {
  "COD PRODUTO": 21779,
  "NOME": "VELHO BARREIRO GARRAFA VIDRO 910ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 720,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 20217,
  "NOME": "ORIGINAL GFA VD 300ML CX C\/23",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 90,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 23095,
  "NOME": "MINUETO WAFER CHOCOLATE PCT 115G CX C\/30",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 108,
  "LASTRO": 11
 },
 {
  "COD PRODUTO": 23594,
  "NOME": "PIRAKIDS BEBIDA LACTEA CHOCOLATE TETRA PAK 200 ML CX C\/27",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 180,
  "LASTRO": 15
 },
 {
  "COD PRODUTO": 20535,
  "NOME": "STELLA ARTOIS ONE WAY 600ML CX C\/12 NPAL",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 80,
  "LASTRO": 16
 },
 {
  "COD PRODUTO": 20537,
  "NOME": "BECKS N ONE WAY 600ML CX C\/12 NPAL",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 80,
  "LASTRO": 16
 },
 {
  "COD PRODUTO": 11102,
  "NOME": "H2OH CITRUS C\/GAS PET 500ML SHRINK C\/12 NPAL",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 168,
  "LASTRO": 24
 },
 {
  "COD PRODUTO": 22200,
  "NOME": "TONICA ANTARCTICA PET 1 L SH C\/06",
  "EMBALAGEM": "1L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 150,
  "LASTRO": 30
 },
 {
  "COD PRODUTO": 22202,
  "NOME": "TONICA ANTARCTICA ZERO PET 1L SH C\/06",
  "EMBALAGEM": "1L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 150,
  "LASTRO": 30
 },
 {
  "COD PRODUTO": 23099,
  "NOME": "CHEEZ-IT SNACK CHEDDAR PCT 29G CX C\/20",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 585,
  "LASTRO": 576
 },
 {
  "COD PRODUTO": 23415,
  "NOME": "POLAR PURO MALTE LATA XSLEEK 350ML SH C 12",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 280,
  "LASTRO": 28
 },
 {
  "COD PRODUTO": 20537,
  "NOME": "BECKS N ONE WAY 600ML CX C\/12 NPAL",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 80,
  "LASTRO": 16
 },
 {
  "COD PRODUTO": 21658,
  "NOME": "SPATEN N LT SLEEK 350ML CX CART C 12",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 280,
  "LASTRO": 28
 },
 {
  "COD PRODUTO": 21668,
  "NOME": "SPATEN N ONE WAY 600ML CX C\/12 NP ARTE",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 80,
  "LASTRO": 16
 },
 {
  "COD PRODUTO": 20530,
  "NOME": "STELLA ARTOIS 600 ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 19729,
  "NOME": "STELLA ARTOIS LT SLEEK 350ML C 8 CX CARTAO",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 400,
  "LASTRO": 40
 },
 {
  "COD PRODUTO": 23731,
  "NOME": "GATORADE MELANCIA-MORANGO PET 500ML SIXPACK",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 42
 },
 {
  "COD PRODUTO": 22003,
  "NOME": "HALLS CEREJA ENVELOPE 28G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 1650,
  "LASTRO": 1650
 },
 {
  "COD PRODUTO": 22005,
  "NOME": "HALLS MENTA ENVELOPE 28G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 1650,
  "LASTRO": 1650
 },
 {
  "COD PRODUTO": 22007,
  "NOME": "HALLS EXTRA FORTE ENVELOPE 28G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 1650,
  "LASTRO": 1650
 },
 {
  "COD PRODUTO": 22507,
  "NOME": "JIM BEAM FIRE GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 480,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 22505,
  "NOME": "JIM BEAM HONEY GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 480,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 21539,
  "NOME": "JIM BEAM WHITE GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 480,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 23120,
  "NOME": "MINUETO ROLINHO WAFER BRIGAD PCT 40G CX C\/24",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 250,
  "LASTRO": 20
 },
 {
  "COD PRODUTO": 23122,
  "NOME": "MINUETO ROLINHO WAFER CHOC PCT 40G CX C\/24",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 250,
  "LASTRO": 20
 },
 {
  "COD PRODUTO": 21968,
  "NOME": "TRIDENT HORTELA ENVELOPE 8G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 3520,
  "LASTRO": 3520
 },
 {
  "COD PRODUTO": 21970,
  "NOME": "TRIDENT MENTA ENVELOPE 8G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 3520,
  "LASTRO": 3520
 },
 {
  "COD PRODUTO": 21532,
  "NOME": "ROCKS DRY GIN GARRAFA VIDRO 995ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 660,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 22543,
  "NOME": "ROCKS STRAMBERRY GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 600,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 21973,
  "NOME": "TRIDENT MELANCIA ENVELOPE 8G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 3520,
  "LASTRO": 3520
 },
 {
  "COD PRODUTO": 23055,
  "NOME": "PIRACANJUBA UHT INTEGRAL CX 1L CX C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 85,
  "LASTRO": 17
 },
 {
  "COD PRODUTO": 23060,
  "NOME": "PIRACANJUBA UHT SEMIDESN CX 1L CX C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 85,
  "LASTRO": 17
 },
 {
  "COD PRODUTO": 22408,
  "NOME": "BRASILBERG GARRAFA VD 920ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 624,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 22405,
  "NOME": "BACARDI BIG APPLE GARRAFA VIDRO 980ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 420,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 22384,
  "NOME": "NATASHA GARRAFA VIDRO 900ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 672,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 21953,
  "NOME": "BOMBAY SAPPHIRE GIN GARRAFA VIDRO 750ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 768,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 21531,
  "NOME": "RAJSKA ORIGINAL GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 660,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 22326,
  "NOME": "BRAHMA DUPLO MALTE LT 473ML SH C\/12 NPAL",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 20533,
  "NOME": "BRAHMA DUPLO MALTE GFA VD 1L",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 50,
  "LASTRO": 10
 },
 {
  "COD PRODUTO": 23216,
  "NOME": "PATAGONIA IPA LATA 473ML 6PACK CARTAO",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 420,
  "LASTRO": 42
 },
 {
  "COD PRODUTO": 23186,
  "NOME": "SPATEN N 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 84,
  "LASTRO": 14
 },
 {
  "COD PRODUTO": 21557,
  "NOME": "MICHELOB ULTRA LONG NECK FLINT 355ML SIX PACK C-4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 56,
  "LASTRO": 7
 },
 {
  "COD PRODUTO": 23271,
  "NOME": "SKOL BEATS SENSES LONG NECK 269ML SIX-PACK SH C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 91,
  "LASTRO": 13
 },
 {
  "COD PRODUTO": 23269,
  "NOME": "SKOL BEATS GT LONG NECK 269ML SIX-PACK SH C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 91,
  "LASTRO": 13
 },
 {
  "COD PRODUTO": 23220,
  "NOME": "PATAGONIA IPA ONE WAY 740ML CX6",
  "EMBALAGEM": 740,
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 140,
  "LASTRO": 28
 },
 {
  "COD PRODUTO": 4293,
  "NOME": "PEPSI BLACK PET 200ML SH C\/12",
  "EMBALAGEM": "CAÇULINHA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 400,
  "LASTRO": 40
 },
 {
  "COD PRODUTO": 20178,
  "NOME": "PEPSI TWIST PET 200ML SH C\/12",
  "EMBALAGEM": "CAÇULINHA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 400,
  "LASTRO": 40
 },
 {
  "COD PRODUTO": 23218,
  "NOME": "PATAGONIA IPA LN 355ML CX C\/12",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 132,
  "LASTRO": 22
 },
 {
  "COD PRODUTO": 22397,
  "NOME": "WALESA GFA PET 966ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 864,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 21786,
  "NOME": "MONTILLA CARTA BRANCA GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 576,
  "LASTRO": 0
 },
 {
  "COD PRODUTO": 19321,
  "NOME": "GUARANA ANTARCTICA ZERO PET 200ML SH C\/12",
  "EMBALAGEM": "CAÇULINHA",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 400,
  "LASTRO": 40
 },
 {
  "COD PRODUTO": 22619,
  "NOME": "SUKITA LIMAO PET 2L CAIXA C\/8",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 75,
  "LASTRO": 75
 },
 {
  "COD PRODUTO": 26462,
  "NOME": "ORIGINAL LT 473ML CX CARTAO C\/12",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 24168,
  "NOME": "MICHELOB ULTRA N LONG NECK 330ML SIX-PACK SHRINK C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 24306,
  "NOME": "RED BULL MELANCIA LATA 250ML FOUR PACK NPAL",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 7979,
  "NOME": "GATORADE FRUTAS CITRICAS PET 500ML SIXPACK",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 21533,
  "NOME": "BLACK STONE GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 22556,
  "NOME": "61 CACHACA GARRAFA VD 970ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 24148,
  "NOME": "CHOCOLEITE BEBIDA LACTEA GFA VD 208 ML CX C\/24",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 24150,
  "NOME": "CHOCOLEITE BEBIDA LACTEA GFA PET 260 ML CX C\/24",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 24152,
  "NOME": "CHOCOLEITE BEBIDA LACTEA GFA PET 880 ML CX C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 21526,
  "NOME": "JOHNNIE WALKER RED LABEL GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 23672,
  "NOME": "CERVEGELA PLASTICA BRAHMA 1 UN P\/ GFA 600ML CX C\/3",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 26461,
  "NOME": "KIT BUDWEISER LONG NECK 330ML 2UN + 1 COPO 350ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 26463,
  "NOME": "KIT STELLA ARTOIS LONG NECK 275ML 1UN + 1 CALICE 250ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 26513,
  "NOME": "KIT BRAHMA DUPLO MALTE LATA 350ML 2 UN + 1 COPO 330ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 26699,
  "NOME": "GUARANA CHP ANTARCTICA PET 2,25L SH C\/6 250ML GRATIS",
  "EMBALAGEM": "2,25L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 24632,
  "NOME": "SUKITA TUBAINA PET 2L SHRINK C\/8",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 26607,
  "NOME": "RED BULL PITAYA LATA 250ML FOUR PACK NPAL",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 4264,
  "NOME": "POLAR PURO MALTE GFA VD 1L",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 20531,
  "NOME": "BECKS N 600 ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 26188,
  "NOME": "STELLA ARTOIS LT 473ML CX CARTAO C\/12",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 22177,
  "NOME": "BUDWEISER ZERO LT SLEEK 350ML C 8 CX CARTAO",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 21791,
  "NOME": "PIRASSUNUNGA 51 GARRAFA VIDRO 965ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 21974,
  "NOME": "TRIDENT TUTTI-FRUTTI ENVELOPE 8G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 26858,
  "NOME": "BRAHMA DUPLO MALTE BLACK LT SLEEK 350ML C 8 CX CARTAO",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 25837,
  "NOME": "SPATEN N LT 473ML CX CARTAO C\/12",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 21020,
  "NOME": "BUDWEISER LT SLEEK 350ML CX CART C 12",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 21976,
  "NOME": "TRIDENT SPEAKMINT ENVELOPE 30.6G CX C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 4262,
  "NOME": "MICHELOB ULTRA N LT SLEEK 350ML C 8 CX CARTAO",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 12952,
  "NOME": "BRAHMA CHOPP ZERO LN 355ML SIXPACK",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 27522,
  "NOME": "CACHACA 51 PIRASSUNUNGA GFA VD 965ML RET CX\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 21880,
  "NOME": "GUARANA CHP ANTARCTICA PET 1L PACK C\/2 MULTPACK NENO",
  "EMBALAGEM": "1L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 22830,
  "NOME": "MONTILLA CARTA OURO GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 22180,
  "NOME": "BUDWEISER ZERO LONG NECK 330ML SIX-PACK SHRINK C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 25220,
  "NOME": "CACHACA 51 PIRASS OURO DESCARTAVEL GFA DE VDRO 965ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 26514,
  "NOME": "KIT COLORADO APPIA GFA VD 600ML 1UN + 1 CALDERETA 350ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 27861,
  "NOME": "KIT STELLA ARTOIS LONG NECK 330ML 4UN+ CALICE 250ML1UN",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 28135,
  "NOME": "KIT PATAGONIA LATA 350ML 4UN+ COPO 473ML 1UN",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 22009,
  "NOME": "CHICLETE ADAMS HORTELA CAIXINHA 2,8G CX C\/100",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 23638,
  "NOME": "STA. RITA TRES MEDALLAS MERLOT GFA VD 750ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 20549,
  "NOME": "BRAHMA DUPLO MALTE GFA VD 300ML CX C\/23",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 28137,
  "NOME": "SKOL BEATS CAIPIRINHA LT 269ML CX CARTAO C\/8 NPAL",
  "EMBALAGEM": "LATA 269",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 27825,
  "NOME": "DOMUS CONHAQUE GARRAFA VIDRO 900ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 23637,
  "NOME": "STA. RITA TRES MEDALLAS CAMERNERE GFA VD 750ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 23636,
  "NOME": "STA. RITA TRES MEDALLAS CAB. SAUV. GFA VD 750ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 27863,
  "NOME": "ALMADEN TINTO SECO MERLOT GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 27841,
  "NOME": "ALMADEN VINHO CABERNET SAUVIGNON BAG IN BOX 3L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 25178,
  "NOME": "51 ICE LIMAO GARRAFA VD 275ML CX C24",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 24094,
  "NOME": "MAGUARY CONC. MANGA GFA PET 500ML PACK C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 24096,
  "NOME": "MAGUARY CONC. MARACUJA GFA PET 500ML PACK C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 27357,
  "NOME": "PIRACANJUBA CREME DE LEITE TETRA PAK 1,03KG CX12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 22104,
  "NOME": "CLUB SOCIAL PCT 24G CX C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 22106,
  "NOME": "MINI OREO PCT 35G CX C\/10",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 24089,
  "NOME": "MAGUARY CONC. CAJU GFA PET 500ML PACK C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 24116,
  "NOME": "MAGUARY CONC. UVA GFA PET 500ML PACK C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 29703,
  "NOME": "BUDWEISER GFA VD 300ML CX C\/23",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 27704,
  "NOME": "MIKES HARD LEMONADE PITAIA N LONG NECK 275ML SIX PACK SH C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 13203,
  "NOME": "ANTARCTICA PILSEN GFA VD 300ML CX C\/23",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 27686,
  "NOME": "MIKES HARD LEMONADE N LONG NECK 275ML SIX PACK SH C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 25174,
  "NOME": "51 ICE BALADA GARRAFA VD 275ML CX C24",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 24479,
  "NOME": "BOHEMIA LONG NECK 330ML SIX-PACK SHRINK C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 29253,
  "NOME": "ORIGINAL GFA VD 1L",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 29199,
  "NOME": "TANG REFRESCO EM PO LARANJA PCT 18G DP C\/18",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 29209,
  "NOME": "TANG REFRESCO EM PO MARACUJA PCT 18G DP C\/18",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 29215,
  "NOME": "TANG REFRESCO EM PO UVA PCT 18G DP C\/18",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 220,
  "LASTRO": 220
 },
 {
  "COD PRODUTO": 25700,
  "NOME": "FUSION PET 2L SHRINK C\/6",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 100,
  "LASTRO": 100
 },
 {
  "COD PRODUTO": 18780,
  "NOME": "CORONITA EXTRA N OW 210ML CX C\/4 SIX PACK",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 28512,
  "NOME": "PEPSI BLACK PET 1,5 SHRINK C\/6",
  "EMBALAGEM": "1,5L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 29485,
  "NOME": "SKOL BEATS CAIPIRINHA LONG NECK 269ML SIX-PACK SH C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 21792,
  "NOME": "WHITE HORSE GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 30045,
  "NOME": "RED BULL BR LATA 473ML CX C 12",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 7979,
  "NOME": "GATORADE FRUTAS CITRICAS PET 500ML SIXPACK",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 7985,
  "NOME": "GATORADE MARACUJA PET 500ML SIXPACK",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 21892,
  "NOME": "NOVECENTO VINHO ARG MALBEC GFA OW 750ML CX C\/6",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 21894,
  "NOME": "NOVECENTO VINHO ARG CABERNET SAUVIGNON GFA OW 750ML CX C\/6",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 13194,
  "NOME": "BRAHMA CHOPP ONE WAY 300ML CX C\/23",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 13015,
  "NOME": "FONTE DA ILHA AGUA M SG PET 300 ML CAIXA C\/ 12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 13017,
  "NOME": "FONTE  DA ILHA AGUA M CG PET 300 ML CAIXA C\/ 12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 23444,
  "NOME": "PATAGONIA AMB LAG NACIONAL 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 24158,
  "NOME": "PATAGONIA IPA 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 5753,
  "NOME": "PEPSI COLA PET 2,25L CAIXA C\/6",
  "EMBALAGEM": "2,25L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 21781,
  "NOME": "SMIRNOFF ICE GARRAFA VD 275ML CX C24",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 21530,
  "NOME": "SMIRNOFF ORIGINAL GARRAFA VIDRO 998ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 23029,
  "NOME": "JOHNNIE WALKER BLACK LABEL GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 25151,
  "NOME": "OLD PARR WHISKY GFA VDR 1L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 27001,
  "NOME": "GORDONS GIN DRY GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 29518,
  "NOME": "JOHNNIE WALKER WHISKY BLONDE GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 21527,
  "NOME": "TANQUERAY GIN LONDON DRY GARRAFA VIDRO 750ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 28202,
  "NOME": "BUBBALOO TUTTI FRUTTI DISPLAY 300G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 28203,
  "NOME": "BUBBALOO MORANGO DISPLAY 300G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 28204,
  "NOME": "BUBBALOO UVA DISPLAY 300G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 29197,
  "NOME": "TANG REFRESCO EM PO LIMAO PCT 18G DP C\/18",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 29201,
  "NOME": "TANG REFRESCO EM PO ABACAXI PCT 18G DP C\/18",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 29207,
  "NOME": "TANG REFRESCO EM PO MORANGO PCT 18G DP C\/18",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 30649,
  "NOME": "ABSOLUT RASPBERRI FRAMBOESA GARRAFA VIDRO 750ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 24573,
  "NOME": "ABSOLUT EXTRAKT GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 27574,
  "NOME": "BALLANTINES BOURBON BARREL GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 21956,
  "NOME": "BALLANTINES 12 YEARS GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 24571,
  "NOME": "ORLOFF VODKA GFA PET 1,75L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 26037,
  "NOME": "MONTILLA CARTA CRISTAL GFA VDR 1L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 26047,
  "NOME": "MALIBU RUM GARRAFA VIDRO 750ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 22562,
  "NOME": "DOMECQ COQ. COMPOSTO GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 21539,
  "NOME": "JIM BEAM WHITE GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 21922,
  "NOME": "MARTINI EXTRA DRY GARRAFA VIDRO 750ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 21924,
  "NOME": "MARTINI ROSSO GARRAFA VIDRO 750ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 11330,
  "NOME": "SKOL GFA 1L DESCARTAVEL",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 22618,
  "NOME": "BRAHMA CHOPP ONE WAY 1L GRFE CX C\/12",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 29991,
  "NOME": "SKOL BEATS SENSES LONG NECK 269ML SIX-PACK SH C\/2",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 6006,
  "NOME": "AGUA MIN FONTE DA ILHA S\/GAS COPO 200ML CAIXA C\/48",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 5596,
  "NOME": "AGUA MIN FONTE DA ILHA S\/GAS PET 500ML CAIXA C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 5594,
  "NOME": "AGUA MIN FONTE DA ILHAC\/GAS PET 500ML CAIXA C\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 5592,
  "NOME": "AGUA MIN FONTE DA ILHA S\/GAS PET 1,5L CAIXA C\/6",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 5943,
  "NOME": "AGUA MIN FONTE DA ILHAC\/GAS PET 2L CAIXA C\/6 SHRINK DECORADO",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 27179,
  "NOME": "HALLS MORANGO ENVELOPE 28G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 22027,
  "NOME": "COLORADO APPIA LT SLEEK 350ML C8 CX CARTAO NPAL",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 104,
  "LASTRO": 104
 },
 {
  "COD PRODUTO": 32067,
  "NOME": "GATORADE BERRY BLUE PET 500ML SIXPACK",
  "EMBALAGEM": "500ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 29974,
  "NOME": "SKOL BEATS GT LONG NECK 269ML SIX-PACK SH C\/2",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 29580,
  "NOME": "STELLA ARTOIS PURE GOLD LONG NECK 330ML SP SH C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32349,
  "NOME": "BEATS TROPICAL LT 269ML CX CARTAO C\/8 NPAL",
  "EMBALAGEM": "LATA 269",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32361,
  "NOME": "BEATS TROPICAL LONG NECK 269ML SIX-PACK SH C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 22561,
  "NOME": "JAMESON STD GARRAFA VIDRO 750ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 23028,
  "NOME": "BUCHANANS WHISKY DELUXE 12 ANOS GARRAFA VIDRO 1 L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32122,
  "NOME": "SMIRNOFF VODKA N21 GFA PET 1,75L",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 29505,
  "NOME": "CIROC VODKA GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 29508,
  "NOME": "JOHNNIE WALKER WHISKY GOLD LABEL RESERVE GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32648,
  "NOME": "BUBBALOO MORANGO DISPLAY 5G CX\/60",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 31856,
  "NOME": "CORONA EXTRA N LT 473ML CX CARTAO C\/12",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32646,
  "NOME": "BUBBALOO TUTTI FRUTTI DISPLAY 5G CX\/60",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30854,
  "NOME": "BUBBALOO BALA MIX DISPLAY 15G CX\/12",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 29654,
  "NOME": "PASSPORT HONEY LICOR GARRAFA VIDRO 670ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 27177,
  "NOME": "HALLS MENTOL ENVELOPE 28G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 26936,
  "NOME": "YPIOCA CONTA GOTAS GOLD GARRAFA VIDRO 965ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 27866,
  "NOME": "CORONA CERO SUNBREW N LONG NECK 330 ML SP BASKET CX C4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 20150,
  "NOME": "BRAHMA CHOPP LT 473ML SH C\/12 NPAL MULTPACK 12",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32473,
  "NOME": "STELLA ARTOIS PURE GOLD LT 473ML CX CARTAO C\/12",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 31962,
  "NOME": "FUSION MELANCIA PET 2L SHRINK C\/6",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 31964,
  "NOME": "FUSION TROPICAL PET 2L SHRINK C\/6",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32969,
  "NOME": "RED BULL SUMMER MORANGO E PESSEGO LATA 250ML FOUR PACK NPAL",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30898,
  "NOME": "LACTA OURO BRANCO WAFER RECHEADO PCT 25G DP C\/15",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30977,
  "NOME": "LACTA SONHO DE VALSA STICK WAFER PCT 25G DP C\/15",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 29495,
  "NOME": "GATORADE ZERO CAL FRUTAS SILV PET 350ML SH C12",
  "EMBALAGEM": "350ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 29493,
  "NOME": "GATORADE ZERO CAL LAR LIMA PET 350ML SH C12",
  "EMBALAGEM": "350ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30942,
  "NOME": "SPATEN N LONG NECK 330ML SIX-PACK SHRINK C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32644,
  "NOME": "BUBBALOO UVA DISPLAY 5G CX\/60",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 11191,
  "NOME": "LIPTON PESSEGO PET 1,5 SHRINK C\/6 HF",
  "EMBALAGEM": "1,5L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 33737,
  "NOME": "BEATS RED MIX LONG NECK 269ML SIX-PACK SH C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 33734,
  "NOME": "BEATS RED MIX LT 269ML SH C\/8",
  "EMBALAGEM": "LATA 269",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 8413,
  "NOME": "GUARANA CHP ANTARCTICA DIET PET 1,5 SHRINK C\/6",
  "EMBALAGEM": "1,5L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 33167,
  "NOME": "PEPSI BLACK PET 600ML SH C\/12 NPAL",
  "EMBALAGEM": "600ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 33738,
  "NOME": "BEATS RED MIX LONG NECK 269ML SIX-PACK SH C\/2",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 1164,
  "NOME": "SUKITA UVA LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "350ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34416,
  "NOME": "FLORESTAL BALA MENTA PCT PLAST 500G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34414,
  "NOME": "FLORESTAL BALA BOLINHA CANELA PCT PLAST 500G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34411,
  "NOME": "FLORESTAL FLOPI BALA LARANJA S AC DISPLAY 480G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34418,
  "NOME": "FLORESTAL FLOPI BALA FRUIT MIX S AC DISPLAY 480G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34654,
  "NOME": "FLOPITO PIRULITO CORACAO VERMELHO PCT PLAST 500G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34655,
  "NOME": "POP KISS PIRULITO CEREJA PCT PLAST 500G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34417,
  "NOME": "FLORESTAL BALINHA CORAC MORANGO PCT PLAST 500G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34405,
  "NOME": "FLORESTAL BALA BRAZILIAN COFFEE PCT PLAST 500G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34459,
  "NOME": "FLORESTAL BALA BRAZILIAN COFFEE PCT PLAST 108G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34412,
  "NOME": "FLORESTAL BALA MASTIG MINT HORTELA PCT PLAST 500G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34413,
  "NOME": "FLORESTAL BALA MASTIG MOLE SORT PCT PLAST 500G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34393,
  "NOME": "FLORESTAL BALA GOMA MINHOCAS AZ PCT PLAST 500G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34656,
  "NOME": "FLOPITO PIRULITO CHICLE CEREJA PCT PLAST 500G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34296,
  "NOME": "TRIDENT CANELA ENVELOPE 8G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34298,
  "NOME": "TRIDENT MORANGO ENVELOPE 8G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 29733,
  "NOME": "HALLS MELANCIA ENVELOPE 28G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 9088,
  "NOME": "SODA LIMONADA ANTARCTICA DIET LATA 350ML SH C\/12 NPAL",
  "EMBALAGEM": "350ML",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 2354,
  "NOME": "SODA LIMONADA ANTARCTICA DIET PET 2L CAIXA C\/6",
  "EMBALAGEM": "2L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 33816,
  "NOME": "ORIGINAL LT 473ML SH C12 NP MULTPACK",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 11103,
  "NOME": "H2OH CITRUS C\/GAS PET 1,5 SHRINK C\/06 NPAL",
  "EMBALAGEM": "1,5L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34429,
  "NOME": "RED BULL SUGAR FREE AMORA LATA 250ML FOUR PACK NPAL",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34420,
  "NOME": "RED BULL SUMMER MARACUJA E MELAO LATA 250ML FOUR PACK NPAL",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34770,
  "NOME": "RED BULL SUGAR FREE POMELO LATA 250ML FOUR PACK NPAL",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34432,
  "NOME": "RED BULL TROPICAL BR LATA 473ML CX C 12",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32685,
  "NOME": "POLAR EXPORT LT 473ML SH C\/12 NPAL MULTPACK 12",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34180,
  "NOME": "LACTA SONHO DE VALSA 1 UN 20G PCT C540G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34178,
  "NOME": "LACTA OURO BRANCO 1 UN 20G PCT C540G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 35003,
  "NOME": "TRIDENT XFRESH 5S PRETO CEREJA ENVELOPE 8G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34126,
  "NOME": "RED BULL SUGAR FREE BR LATA 355ML FOUR PACK",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34263,
  "NOME": "CORONA CERO SUNBREW N LT SLEEK 350ML C 8 CX CARTAO",
  "EMBALAGEM": "LATA 350ML",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34460,
  "NOME": "FLORESTAL BALINHA CORAC MORANGO PCT PLAST 108G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34780,
  "NOME": "FLORESTAL BALA GOMA SININHOS PCT PLAST 150G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34782,
  "NOME": "FLORESTAL BALA GOMA BANANAS PCT PLAST 150G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34783,
  "NOME": "FLORESTAL BALA MASTIG MOLE SORT PCT PLAST 100G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34820,
  "NOME": "FLORESTAL BALA MENTA PCT PLAST 122G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34821,
  "NOME": "FLORESTAL BALA BOLINHA CANELA PCT PLAST 122G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34977,
  "NOME": "FLOPITO PIRULITO CORACAO VERMELHO PCT 120G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 24408,
  "NOME": "QUINTA DO MORGADO VINHO TINTO SECO GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 24409,
  "NOME": "QUINTA DO MORGADO VINHO TINTO SUAVE GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 24411,
  "NOME": "QUINTA DO MORGADO VINHO BRANCO SECO GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 31795,
  "NOME": "BRUTAL FRUIT LONG NECK 275ML SIX PACK SH C 2",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 20164,
  "NOME": "SKOL LT 473ML SH C\/12 NPAL MULTPACK 12",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34410,
  "NOME": "HALLS UVA VERDE ENVELOPE 28G CX C\/21",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32785,
  "NOME": "CORONA EXTRA N ONE WAY 600ML GARRAFEIRA C\/24",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32749,
  "NOME": "CORONA EXTRA N 600ML",
  "EMBALAGEM": "1\/1",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32683,
  "NOME": "ANTARCTICA PILSEN LT 473ML SH C\/12 NPAL MULTPACK 12",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 35331,
  "NOME": "BUDWEISER GFA VD 1L",
  "EMBALAGEM": "LITRO",
  "TIPO": "Cerveja",
  "TIPOV": "RGB",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 35617,
  "NOME": "BEATS GREEN MIX LT 269ML SH C\/8",
  "EMBALAGEM": "LATA 269",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 35623,
  "NOME": "BEATS GREEN MIX LONG NECK 269ML SIX-PACK SH C\/2",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 35620,
  "NOME": "BEATS GREEN MIX LONG NECK 269ML SIX-PACK SH C\/4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 35113,
  "NOME": "FLYING FISH LONG NECK 330 ML SIX-PACK SH C 4",
  "EMBALAGEM": "LONG NECK",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 35306,
  "NOME": "FLYING FISH LT 473ML SH C\/12 NPAL",
  "EMBALAGEM": "LATÃO 473",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 36434,
  "NOME": "RED BULL ZERO BR LATA 250ML FOUR PACK NPAL",
  "EMBALAGEM": "RED BULL",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 11556,
  "NOME": "GUARANA ANTARCTICA ZERO PET 1L CAIXA C\/6",
  "EMBALAGEM": "1L",
  "TIPO": "NAB",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 24265,
  "NOME": "SALTON CHAL. VINHO TINTO SUAVE GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 24266,
  "NOME": "SALTON CHAL. VINHO TINTO SECO GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 24267,
  "NOME": "SALTON CHAL. VINHO BRANCO SECO GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 24486,
  "NOME": "GALLO AZEITE OLIVA EX. VIR. GFA VDR 500ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 25329,
  "NOME": "SALTON ESPUMANTE BRUT GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 25332,
  "NOME": "SALTON ESPUMAMTE DEMI SEC GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 25333,
  "NOME": "SALTON ESPUMANTE MOSCATEL GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 25335,
  "NOME": "SALTON ESPUMANTE BRUT ROSE GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 25340,
  "NOME": "SALTON ESPUMANTE PROSECCO BRUT GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 25342,
  "NOME": "SALTON ESPUMANTE CLASSIC BRUT GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 25343,
  "NOME": "SALTON ESPUMANTE CLASSIC DEMI SEC GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 25345,
  "NOME": "SALTON ESPUMANTE CLASSIC DEMI SEC ROSE GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 25347,
  "NOME": "SALTON ESPUMANTE CLASSIC MOSCATEL GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 29170,
  "NOME": "YPE LAVA LOUCAS LIQUIDO NEUTRO FRASCO PLASTICO 500ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 29488,
  "NOME": "SALTON VINHO LUNAE BRANCO GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 29489,
  "NOME": "SALTON VINHO CHALISE BRANCO GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 29507,
  "NOME": "SALTON VINHO CLASSIC CORTE TINTO SUAVE GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30412,
  "NOME": "YPE CLEAR LAVA LOUCAS FRASCO PLASTICO 500ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32354,
  "NOME": "YPE LAVA LOUCAS LIQUIDO CLEAR FRASCO PLAST 500ML CX\/6",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 32355,
  "NOME": "YPE LAVA LOUCAS LIQUIDO NEUTRO FRASCO PLAST 500ML CX\/6",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34192,
  "NOME": "SALTON VINHO CLASSIC MERLOT GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34193,
  "NOME": "SALTON VINHO CLASSIC TANNAT GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34195,
  "NOME": "SALTON VINHO LUNAE ROSE GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34196,
  "NOME": "SALTON VINHO CHALISE ROSE SUAVE GFA VD 750 ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34197,
  "NOME": "PRESIDENTE VODKA GARRAFA VIDRO 900ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34198,
  "NOME": "PRESIDENTE CACHACA GARRAFA VIDRO 900ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 34978,
  "NOME": "FLOPITO PIRULITO CHICLE CEREJA PCT 120G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 36051,
  "NOME": "FLORESTAL MARSHMALLOW  FOF TW COLOR PCT PLAST 220G",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 36391,
  "NOME": "FLORESTAL DROPS BRAZILIAN COFFEE PCT 30G DISPLAY C10",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 36393,
  "NOME": "FLORESTAL DROPS MENTA PCT 30G DISPLAY C10",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 36395,
  "NOME": "FLORESTAL DROPS CEREJA PCT 30G DISPLAY C10",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30411,
  "NOME": "YPE LAVA LOUCAS LIQ MACA FRASCO PLASTICO 500ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 13196,
  "NOME": "SKOL ONE WAY 300ML CX C\/23",
  "EMBALAGEM": "LITRINHO",
  "TIPO": "Cerveja",
  "TIPOV": "OW",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 23673,
  "NOME": "CERVEGELA PLASTICA SKOL 1 UN P\/ GFA 1L CX C\/3",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 23674,
  "NOME": "CERVEGELA PLASTICA SKOL 1 UN P\/ GFA 600ML CX C\/3",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 27773,
  "NOME": "CERVEGELA PLASTICA ANTARCTICA 1 UN P\/ GFA 600ML CX C\/3",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 35108,
  "NOME": "CERVEGELA PLASTICA SPATEN 1 UN P\/ GFA 600ML CX3",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 36234,
  "NOME": "CERVEGELA ALUMINIO ORIGINAL BEGE 1 UN AL P\/ GFA 600 ML CX3",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 37700,
  "NOME": "CERVEGELA PLAST STELLA ARTOIS 1 UN P\/ GFA 600ML CX C\/3 2026",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 25303,
  "NOME": "GARRAFEIRA PL. PRETO BEES 1 UN P\/24 GFA 600ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 25546,
  "NOME": "GARRAFEIRA PL. AL. LAT. AB. PRETA BEES 1 UN P\/ 23 GFA 300ML",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30191,
  "NOME": "ISABELA WAFER MORANGO PCT PLAST 100G CX 40",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30193,
  "NOME": "ISABELA WAFER CHOCOLATE PCT PLAST 100G CX 40",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30195,
  "NOME": "ISABELA WAFER LIMAO PCT PLAST 100G CX 40",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30197,
  "NOME": "ISABELA WAFER CHOCOLATE SUICO PCT PLAST 100G CX 40",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30199,
  "NOME": "ISABELA BISC MOUSSE CHOCOMEIO AMARGO PCT 130G CX C\/50",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30249,
  "NOME": "ISABELA TORTINHAS MORANGO PCT 140G CX C\/50",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30251,
  "NOME": "ISABELA TORTINHAS TORTA DE LIMAO PCT 140G CX C\/50",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 30253,
  "NOME": "ISABELA TORTINHAS CHOCOLATE PCT 140G CX C\/50",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 35726,
  "NOME": "ISABELA BISCOITO AGUA E SAL PCT 350G CX 24",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },
 {
  "COD PRODUTO": 37632,
  "NOME": "ISABELA MARIA BISC DOCE PCT 350G CX 24",
  "TIPO": "MKT",
  "TIPOV": "MARKETPLACE",
  "QTD PALLET": 294,
  "LASTRO": 294
 },

 {
    "COD PRODUTO": 33641,
    "NOME": "BALLANTINES 10 YEARS GARRAFA VIDRO 1 L",
    "EMBALAGEM": "",
    "TIPO": "MKT",
    "TIPOV": "",
    "QTD PALLET": 960,
    "LASTRO": 0
  },
  {
    "COD PRODUTO": 24289,
    "NOME": "ELMA CHIPS AMENDOIM JAPONES PCT 145G CX C/16",
    "EMBALAGEM": "",
    "TIPO": "MKT",
    "TIPOV": "",
    "QTD PALLET": 360,
    "LASTRO": 100
  },
  {
    "COD PRODUTO": 35324,
    "NOME": "ELMA CHIPS AMENDOIM OVINHO PCT 145G CX C26",
    "EMBALAGEM": "",
    "TIPO": "MKT",
    "TIPOV": "",
    "QTD PALLET": 360,
    "LASTRO": 100
  },
  {
    "COD PRODUTO": 35686,
    "NOME": "ELMA CHIPS RUFFLES SAL PCT 68G CX C25",
    "EMBALAGEM": "",
    "TIPO": "MKT",
    "TIPOV": "",
    "QTD PALLET": 360,
    "LASTRO": 100
  },
  {
    "COD PRODUTO": 36034,
    "NOME": "BUDWEISER LT 473ML SH C12 NP MULTIPACK",
    "EMBALAGEM": "LATÃO 473",
    "TIPO": "Cerveja",
    "TIPOV": "OW",
    "QTD PALLET": 220,
    "LASTRO": 22
  },
  {
    "COD PRODUTO": 37144,
    "NOME": "BRAHMA CHOPP ZERO LT 473ML SH C12 NP",
    "EMBALAGEM": "LATÃO 473",
    "TIPO": "Cerveja",
    "TIPOV": "OW",
    "QTD PALLET": 220,
    "LASTRO": 22
  },
  {
    "COD PRODUTO": 35338,
    "NOME": "BUDWEISER ZERO LT 473ML SH C/12 NPAL",
    "EMBALAGEM": "LATÃO 473",
    "TIPO": "Cerveja",
    "TIPOV": "OW",
    "QTD PALLET": 220,
    "LASTRO": 22
  },
  {
    "COD PRODUTO": 24410,
    "NOME": "QUINTA DO MORGADO VINHO BRANCO SUAVE GFA VD 750 ML",
    "EMBALAGEM": "",
    "TIPO": "MKT",
    "TIPOV": "",
    "QTD PALLET": 840,
    "LASTRO": 0
  },
  {
    "COD PRODUTO": 24413,
    "NOME": "QUINTA DO MORGADO VINHO BORDO MEIO SECO GFA VD 750 ML",
    "EMBALAGEM": "",
    "TIPO": "MKT",
    "TIPOV": "",
    "QTD PALLET": 840,
    "LASTRO": 0
  },
  {
    "COD PRODUTO": 36213,
    "NOME": "NUTRATA  CARAMELO PCT 45G DISPLAY C12",
    "EMBALAGEM": "",
    "TIPO": "MKT",
    "TIPOV": "",
    "QTD PALLET": 360,
    "LASTRO": 20
  },
  {
    "COD PRODUTO": 36205,
    "NOME": "NUTRATA YOPRO MORANGO CHOC BRANCO PCT 55G DISPLAY C12",
    "EMBALAGEM": "",
    "TIPO": "MKT",
    "TIPOV": "",
    "QTD PALLET": 360,
    "LASTRO": 20
  },
  {
    "COD PRODUTO": 36208,
    "NOME": "NUTRATA YOPRO BARRA CHOCOLATE PCT 55G DISPLAY C12",
    "EMBALAGEM": "",
    "TIPO": "MKT",
    "TIPOV": "",
    "QTD PALLET": 360,
    "LASTRO": 20
  },
  {
    "COD PRODUTO": 36192,
    "NOME": "NUTRATA BARRA WHEY GREGO BRIGADEIRO PCT 40G DISPLAY C12",
    "EMBALAGEM": "",
    "TIPO": "MKT",
    "TIPOV": "",
    "QTD PALLET": 360,
    "LASTRO": 20
  },
  {
    "COD PRODUTO": 36200,
    "NOME": "NUTRATA BARRA WHEY  DULCE DE LECHE  PCT 40G DISPLAY C12",
    "EMBALAGEM": "",
    "TIPO": "MKT",
    "TIPOV": "",
    "QTD PALLET": 360,
    "LASTRO": 20
  },
  {
    "COD PRODUTO": 36203,
    "NOME": "NUTRATA BARRA WHEY BROWNIE PCT 40G DISPLAY C12",
    "EMBALAGEM": "",
    "TIPO": "MKT",
    "TIPOV": "",
    "QTD PALLET": 360,
    "LASTRO": 20
  }
]
